### ISSUE TITLE
TypeError in dPULearn fit function

### ISSUE THREAD

**Issue by annachernysheva179** [breimanntools/aaanalysis#2]
Hi,
I got the following error message: 
![image](https://github.com/breimanntools/aaanalysis/assets/131196587/ad8884ca-0791-44a1-8dc9-1bceda97d2eb)
I have checked, there is no such argument in check_X function in _utils/check_data.py:
![image](https://github.com/breimanntools/aaanalysis/assets/131196587/cdcb431f-0d85-491b-8757-6569f03972ef)

**Comment by breimanntools** [comment]
Thank you for bringing this issue to our attention. The error has been addressed in the latest version available on GitHub. We plan to release the updated pip version (0.1.3) at the beginning of January.
