### ISSUE TITLE
load_scales fail to handle int64s

### ISSUE THREAD

**Issue by B1RO** [breimanntools/aaanalysis#3]
The provided demo code crashes, because the loaded scales contains int64 dtype columns, which your code can't handle. 
The code crashes during CPP, the int64s are created in load_scales. If you convert the int64 to python ints (which should be able to fit the int64) it works. I'd recommend to either include this fix in your codebase, or  handle int64s. Thanks

aa.options["verbose"] = False
df_scales = aa.load_scales()
df_scales = df_scales.astype({col: int for col in df_scales.select_dtypes(include='int64').columns})
non_numeric_columns = df_scales.select_dtypes(exclude=[np.number]).columns.tolist()
dict_dtype = dict(df_scales.dtypes)
non_numeric_columns2 =  [(col, dict_dtype[col]) for col in dict_dtype if dict_dtype[col] not in [np.number, int, float]]
df_seq = aa.load_dataset(name="DOM_GSEC", n=50)

**Comment by breimanntools** [comment]
Thank you for highlighting this issue. We have corrected it in the latest GitHub version. A new pip release (0.1.3) incorporating this fix is scheduled for early January.

**Comment by breimanntools** [comment]
Solved with new release (1.3 or greater)
