### ISSUE TITLE
DOM_GSEC.tsv

### ISSUE THREAD

**Issue by B1RO** [breimanntools/aaanalysis#4]
Documentation regarding dataset.

Hello, I was wondering whether you could provide some information regarding the DOM_GSEC dataset.

Your .tsv file contains the following entry:

Q14802	MQKVTLGLLVFLAGFPVLDANDLEDKNSPFYYDWHSLQVGGLICAGVLCAMGIIIVMSAKCKCKFGQKSGHHPGETPPLITPGSAQS	0	37	59	NSPFYYDWHS	LQVGGLICAGVLCAMGIIIVMSA	KCKCKFGQKS

or as an object:

entry                                                   Q14802
sequence     MQKVTLGLLVFLAGFPVLDANDLEDKNSPFYYDWHSLQVGGLICAG...
label                                                        0
tmd_start                                                   37
tmd_stop                                                    59
jmd_n                                               NSPFYYDWHS
tmd                                    LQVGGLICAGVLCAMGIIIVMSA
jmd_c                                               KCKCKFGQKS

the problem is that if you look into uniprot, 

extracelluar domain (I believe this is jmd_n) is: NDLEDKNSPFYYDWHSLQ
transmembrane domain is: VGGLICAGVLCAMGIIIVMSA
cytoplasmic domain is (I believe this to be jmd_c): KCKCKFGQKSGHHPGETPPLITPGSAQS

and I can't resolve the difference.
I mean, the transmembrane domain seems to correspond to the entry in uniprot, the jmd_n terminal seems to be a random substring of the extracelluar domain, and the jmd_c seems to be only the first third of the cytoplasmic domain. Could you elaborate why? Thanks!

**Comment by breimanntools** [comment]
For the DOM_GSEC (domain level gamma-secretase substrate) dataset, 'TMD' refers to the Transmembrane Domain, while 'JMD-N' and 'JMD-C' represent the Juxtamembrane Domain N-terminal and C-terminal, respectively, situated adjacent to the TMD. AAanalysis was initially designed around this dataset, and a detailed paper on this subject is in preparation for submission. Broadly in AAanalysis, 'TMD' is defined as 'Target Middle Domain,' and 'JMD' stands for 'Juxta target Middle Domain.' These terminologies and their applications are elaborated in the 'SequenceFeature' class.

**Comment by breimanntools** [comment]
Detailed explaination of terminology is added in note for SequenceFeature (https://aaanalysis.readthedocs.io/en/latest/generated/aaanalysis.SequenceFeature.html#aaanalysis.SequenceFeature)
