### ISSUE TITLE
Doccumentation Image error

### ISSUE THREAD

**Issue by Acva11235** [breimanntools/aaanalysis#5]
# Doccumentation image display error

In the "README.rst" file, there is an attempt to showcase two images, but unfortunately, they are currently unreachable.

Links:
[Build status](https://github.com/breimanntools/aaanalysis/workflows/Build/badge.svg)
[Python-check](https://github.com/breimanntools/aaanalysis/workflows/Python-check/badge.svg)
[Conda - Package Version](https://anaconda.org/conda-forge/aaanalysis/badges/version.svg)

![image](https://github.com/breimanntools/aaanalysis/assets/122595370/7518203d-3fee-48cd-8a1e-2fc5d5b461f2)

## My suggestion:
 - To update the links
 - To remove the links all together

**Comment by breimanntools** [comment]
Thank you for letting me known. The links for these badges are not working yet. This will be fixed as soon as the package reached it beta status (hopefully within the next two to three weeks).

**Comment by Acva11235** [comment]
If you tell me what were the exact badges, I can create a pull request with the necessary modifications

**Comment by breimanntools** [comment]
Thank you for the suggestion. I plan to establish a continuous integration pipeline once the alpha version of the project is complete. This will allow us to integrate 'Build Status' and 'Python Check' badges for enhanced monitoring and quality assurance. Following this, we'll proceed with adding the 'Conda' badge as well.

**Comment by breimanntools** [comment]
All badges are working now
